import type { Asset } from './types'

export const assetsMock: Asset[] = [
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    balance: 1.245,
    priceUsd: 83000,
    valueUsd: 103335,
    change24hPct: 2.1,
    allocationPct: 67.5,
    chain: 'Ethereum',
    riskTag: 'Low',
  },
  {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    balance: 6.8,
    priceUsd: 3200,
    valueUsd: 21760,
    change24hPct: 1.4,
    allocationPct: 14.2,
    chain: 'Ethereum',
    riskTag: 'Low',
  },
  {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    balance: 95,
    priceUsd: 142,
    valueUsd: 13490,
    change24hPct: 7.9,
    allocationPct: 8.8,
    chain: 'Solana',
    riskTag: 'Medium',
  },
  {
    id: 'link',
    symbol: 'LINK',
    name: 'Chainlink',
    balance: 380,
    priceUsd: 19.8,
    valueUsd: 7524,
    change24hPct: 3.2,
    allocationPct: 4.9,
    chain: 'Ethereum',
    riskTag: 'Medium',
  },
  {
    id: 'usdc',
    symbol: 'USDC',
    name: 'USD Coin',
    balance: 4500,
    priceUsd: 1,
    valueUsd: 4500,
    change24hPct: 0,
    allocationPct: 2.9,
    chain: 'Polygon',
    riskTag: 'Low',
  },
  {
    id: 'arb',
    symbol: 'ARB',
    name: 'Arbitrum',
    balance: 2400,
    priceUsd: 1.24,
    valueUsd: 2976,
    change24hPct: -3.5,
    allocationPct: 1.7,
    chain: 'Arbitrum',
    riskTag: 'High',
  },
]
